---
- name: install system packages
  apt: name={{item}} state=present
  with_items:
     - python-pip
     - python-dev
     - python-pythonmagick
     - libpq-dev
     - libopencv-dev
     - python-opencv
     - pdftk
     - git
     - python3-pip

- name: remove libdc1394 error
  command: ln /dev/null /dev/raw1394
  register: command_result
  ignore_errors: True

- name: upgrade pip
  pip: name=pip extra_args='-U'

- name: install pyPdf
  pip: name=pyPdf

- name: install ipdb
  pip: name=ipdb

- git: repo=https://github.com/openstax/test-automation.git
       dest=/vagrant/src/test-automation
       update=no

- name: install ox_inspect
  command: python2.7 setup.py install
           chdir=/vagrant/src/test-automation/inspection

- git: repo=https://github.com/rich-hart/test_auto_ui.git
       dest=/vagrant/src/test_auto_ui
       update=no

- name: install django server
  command: pip3 install -r requirements/base.txt
           chdir=/vagrant/src/test_auto_ui

- name: create database user
  command: psql -U postgres -d postgres -c "CREATE USER openstax WITH SUPERUSER PASSWORD 'openstax';"

- name: create database
  command: createdb -U postgres -O openstax qa_automation

- name: migrate database
  command: python3 manage.py migrate
           chdir=/vagrant/src/test_auto_ui

#- name: run server
#  command: python3 manage.py runserver 192.168.24.48:8001
#           chdir=/vagrant/src/test_auto_ui

 
