---
- name: update apt-cache
  apt: update_cache=yes

- name: install system packages
  apt: name={{item}} state=present
  with_items:
     - python-pip
     - python-dev
     - python-pythonmagick
     - libpq-dev
     - libopencv-dev
     - python-opencv
     - pdftk
     - git


- name: remove libdc1394 error
  command: ln /dev/null /dev/raw1394
  register: command_result
  ignore_errors: True

- name: upgrade pip
  pip: name=pip extra_args='-U'

- name: upgrade pip
  pip: name=pyPdf

- git: repo=https://github.com/openstax/test-automation.git
       dest=/vagrant/src
       update=no
- name: install ox_inspect
  command: python setup.py install
           chdir=/vagrant/src/inspection
  


